credentials:
    usernames:
        psgrigoletti:
            email: eronejs@email
            name: eron
            password: $2b$12$yflRg6v7OV1aCj62sqVGQe3q3SbemGJcozI0seXdUlbuFITyGhWaW
        guest:
            email: guest@email
            name: Visitante
            password: $2b$12$yflRg6v7OV1aCj62sqVGQe3q3SbemGJcozI0seXdUlbuFITyGhWaW


cookie:
    expiry_days: 30
    key: random_signature_key # Must be string
    name: random_cookie_name
